name: Manual Build

env:
  # cargo-nextest version to build
  NEXTEST_VERSION: "0.9.140"

on:
  # To run manually workflow
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build cargo-nextest
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
    # Checkout only build script and script for CI
    - name: Checkout build script
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      with:
        sparse-checkout: |
          build.sh
          ci/openbsd_build.sh

    # Prepare OpenBSD-stable VM and run build
    - name: Start OpenBSD VM
      uses: cross-platform-actions/action@5ea7e8e4677bd726033a10b094ba1c5762b15dee  # v1.3.0
      with:
        operating_system: openbsd
        version: '7.9'
        sync_files: true
        environment_variables: NEXTEST_VERSION

    - name: Build on OpenBSD
      shell: cpa.sh {0}
      # implementation modelled from https://github.com/rust-lang/rustup/blob/master/.github/workflows/ci.yaml
      # * NOTE: All steps need to be run in this block, otherwise, we are operating back on the Ubuntu host
      run: |
        # Install requirements to build cargo-nextest
        echo "::group::Install requirements"
        sudo pkg_add -I rust zstd
        sudo hostname -s openbsd-ci
        echo "::endgroup::"
        echo "::group::OS Infos"
        uname -a
        rustc -vV
        echo "::endgroup::"
        echo "::group::Build cargo-nextest"
        bash ci/openbsd_build.sh
        echo "::endgroup::"

    # Run commands on Ubuntu host
    - name: Check artifact on Ubuntu runner
      run: |
        sudo apt-get install -y file
        echo "# pwd"
        pwd
        echo "# ls -l cargo-nextest-build/target/release/cargo-nextest"
        ls -l cargo-nextest-build/target/release/cargo-nextest
        echo "# Check cargo-nextest file"
        file cargo-nextest-build/target/release/cargo-nextest

    # Upload artifact for cargo-nextest binary
    - name: Upload cargo-nextest binary
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  #v7.0.1
      with:
        name: cargo-nextest-${{ env.NEXTEST_VERSION }}-openbsd
        # Wildcard used to flatten directory hierarchy
        path: cargo-nextest-build/target/release/*-nextest
        if-no-files-found: error
        retention-days: 0
